/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectotransferencia.presentacion;

import javax.swing.JOptionPane;
import proyectotransferencia.dtos.NuevaTransferenciaDTO;
import proyectotransferencia.negocio.ITransferenciaBO;
import proyectotransferencia.negocio.NegocioException;

/**
 *
 * @author PC MASTER RACE
 */

public class ConfirmarTransferenciaFORM extends javax.swing.JFrame {
    
    private final ITransferenciaBO transferenciaBO;
    private final NuevaTransferenciaDTO nuevaTransferencia;

    /**
     * Creates new form ConfirmarTransferenciaFORM
     */
    public ConfirmarTransferenciaFORM(
            ITransferenciaBO transferenciaBO,
            NuevaTransferenciaDTO nuevaTransferencia,
            String cuentaOrigen,
            String cuentaDestino,
            Float saldoAntes,
            Float saldoDespues,
            String fecha) {

        this.transferenciaBO = transferenciaBO;
        this.nuevaTransferencia = nuevaTransferencia;

        initComponents(); 

        lblCuentaOrigen.setText(cuentaOrigen);
        lblCuentaDestino.setText(cuentaDestino);
        lblFecha.setText(fecha);
        lblSaldoAntes.setText(String.valueOf(saldoAntes));
        lblSaldoDespues.setText(String.valueOf(saldoDespues));
        lblMonto.setText(String.valueOf(nuevaTransferencia.getMonto()));
        lblConcepto.setText(nuevaTransferencia.getConcepto());
    }

    private void confirmar() {
        try {
            transferenciaBO.crearTransferencia(nuevaTransferencia);

            JOptionPane.showMessageDialog(this,
                    "Transferencia realizada con éxito",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);

            this.dispose();

        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCuentaOrigen = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblCuentaDestino = new javax.swing.JLabel();
        lblSaldoAntes = new javax.swing.JLabel();
        lblSaldoDespues = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        lblConcepto = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAceptar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCuentaOrigen.setText("Cuenta Origen");

        lblFecha.setText("Cuenta Destino");

        lblCuentaDestino.setText("Cuenta Destino");

        lblSaldoAntes.setText("Saldo Antes");

        lblSaldoDespues.setText("Saldo Antes");

        lblMonto.setText("Monto");

        lblConcepto.setText("Monto");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAceptar1.setText("Aceptar");
        btnAceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCuentaDestino)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSaldoAntes)
                        .addGap(82, 82, 82)
                        .addComponent(lblSaldoDespues)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(lblMonto)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCuentaOrigen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblConcepto)
                                .addGap(38, 38, 38))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAceptar1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addComponent(btnCancelar)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuentaOrigen)
                    .addComponent(lblConcepto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(lblCuentaDestino)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar1))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaldoAntes)
                    .addComponent(lblSaldoDespues)
                    .addComponent(lblMonto))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar1ActionPerformed
        this.confirmar();
    }//GEN-LAST:event_btnAceptar1ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar1;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblConcepto;
    private javax.swing.JLabel lblCuentaDestino;
    private javax.swing.JLabel lblCuentaOrigen;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblSaldoAntes;
    private javax.swing.JLabel lblSaldoDespues;
    // End of variables declaration//GEN-END:variables
}
