/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectotransferencia.presentacion;

import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import proyectotransferencia.entidades.Cuenta;
import proyectotransferencia.entidades.RetiroSinCuenta;
import proyectotransferencia.negocio.IClientesBO;
import proyectotransferencia.negocio.ICuentaBO;
import proyectotransferencia.negocio.IOperacionesBO;
import proyectotransferencia.negocio.IRetiroSinCuentaBO;
import proyectotransferencia.negocio.ITransferenciaBO;
import proyectotransferencia.negocio.NegocioException;

/**
 *
 * @author PC GAMER MASTER RACE
 */
public class ConfirmacionRetiroSinCuentaFORM extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConfirmacionRetiroSinCuentaFORM.class.getName());
    private final IRetiroSinCuentaBO retiroBO;
    private final ICuentaBO cuentaBO;
    private final IOperacionesBO operacionesBO;
    private final ITransferenciaBO transferenciaBO;
    private final IClientesBO clientesBO;

    /**
     * Creates new form ConfirmacionRetiroSinCuentaFORM
     */
    public ConfirmacionRetiroSinCuentaFORM(IRetiroSinCuentaBO retiroBO,ICuentaBO cuentaBO, IOperacionesBO operacionesBO, ITransferenciaBO transferenciaBO, IClientesBO clientesBO) {
        this.retiroBO = retiroBO;
        this.cuentaBO = cuentaBO;
        this.operacionesBO = operacionesBO;
        this.transferenciaBO = transferenciaBO;
        this.clientesBO = clientesBO;
        initComponents();
        txtFechaHoraCobro.setEditable(false);
    }
    
    private void retirar(){
        try{
            if(txtIngreseElFolio.getText().isEmpty()){
                throw new NegocioException("Ingrese el folio", null);
            }

            if(txtContrasenia.getText().isEmpty()){
                throw new NegocioException("Ingrese la contraseña", null);
            }

            Integer folio = Integer.parseInt(txtIngreseElFolio.getText());

            String contraseña = txtContrasenia.getText();

            RetiroSinCuenta retiro = retiroBO.obtenerReitroPorFolioYContraseña(folio, contraseña);

            if(retiro == null){
                throw new NegocioException("Folio o contraseña incorrectos",null);
            }

            if(retiro.getFechaHoraCobro() != null){
                throw new NegocioException("Este retiro ya fue cobrado", null);
            }

            GregorianCalendar ahora = new GregorianCalendar();
            long diferencia = ahora.getTimeInMillis() - retiro.getFechaHoraSolicitud().getTimeInMillis();
            long minutos =diferencia / (1000 * 60);

            if(minutos > 10){
                throw new NegocioException("Retiro expirado", null);
            }

            Cuenta cuenta = retiro.getOperacion().getCuenta();
            Float monto = retiro.getMonto();
            cuentaBO.retirar(cuenta.getIdCuenta(), monto);
            retiroBO.actualizarFechaCobro(folio, ahora);

            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");

            txtFechaHoraCobro.setText(formato.format(ahora.getTime()));

            JOptionPane.showMessageDialog(
                    this,
                    "RETIRO EXITOSO\n\n" +
                    "Monto: $" + monto + "\n" +
                    "Fecha: " +
                    formato.format(
                            ahora.getTime()
                    )
            );

        }catch(NegocioException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRetiroSinCuenta = new javax.swing.JLabel();
        lblIngreseFolio = new javax.swing.JLabel();
        txtIngreseElFolio = new javax.swing.JTextField();
        lblContrasenia = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JTextField();
        btnRetirar = new javax.swing.JButton();
        lblFechayHoraDeCobro = new javax.swing.JLabel();
        txtFechaHoraCobro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRetiroSinCuenta.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblRetiroSinCuenta.setText("Confiirmacion De RetiroSinCuenta");

        lblIngreseFolio.setText("Ingrese El Folio:");
        lblIngreseFolio.setToolTipText("");

        lblContrasenia.setText("Contraseña:");

        btnRetirar.setText("RETIRAR");
        btnRetirar.addActionListener(this::btnRetirarActionPerformed);

        lblFechayHoraDeCobro.setText("Fecha Y Hora de Cobro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblRetiroSinCuenta)
                        .addGap(0, 52, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIngreseFolio)
                            .addComponent(lblContrasenia)
                            .addComponent(lblFechayHoraDeCobro))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIngreseElFolio)
                            .addComponent(txtContrasenia)
                            .addComponent(txtFechaHoraCobro))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(btnRetirar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRetiroSinCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIngreseFolio)
                    .addComponent(txtIngreseElFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasenia)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechayHoraDeCobro)
                    .addComponent(txtFechaHoraCobro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnRetirar)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
       this.retirar();
       LoginFORM form = new LoginFORM(clientesBO, cuentaBO, transferenciaBO, operacionesBO, retiroBO);
       form.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnRetirarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetirar;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblFechayHoraDeCobro;
    private javax.swing.JLabel lblIngreseFolio;
    private javax.swing.JLabel lblRetiroSinCuenta;
    private javax.swing.JTextField txtContrasenia;
    private javax.swing.JTextField txtFechaHoraCobro;
    private javax.swing.JTextField txtIngreseElFolio;
    // End of variables declaration//GEN-END:variables
}
