/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectotransferencia.presentacion;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JOptionPane;
import proyectotransferencia.dtos.NuevaOperacionDTO;
import proyectotransferencia.entidades.Cuenta;
import proyectotransferencia.negocio.ICuentaBO;
import proyectotransferencia.negocio.IOperacionesBO;
import proyectotransferencia.negocio.NegocioException;

/**
 *
 * @author PC GAMER MASTER RACE
 */
public class CrearOperacionFORM extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrearOperacionFORM.class.getName());
    private final IOperacionesBO operacionesBO;
    private final ICuentaBO cuentaBO;
    
    public CrearOperacionFORM(IOperacionesBO operacionesBO, ICuentaBO cuentaBO) {
        this.cuentaBO = cuentaBO;
        this.operacionesBO =  operacionesBO;
        initComponents();
        cargarTiposOperacion();
        cargarCuentas();
        btnContinuar.addActionListener(e -> crearOperacion());
        btnSalir.addActionListener(e -> dispose());
        GregorianCalendar calendario = new GregorianCalendar();
        Date fechaActual = calendario.getTime();

        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

        txtFechaHora.setText(formato.format(fechaActual));
        txtFechaHora.setEditable(false);
    }
    
    private void cargarCuentas() {
        cmbIdCuenta.removeAllItems();

        try {
            cuentaBO.obtenerCuenta();
            List<Cuenta> cuentas = cuentaBO.obtenerCuenta();

            for (Cuenta cuenta : cuentas) {
                
                cmbIdCuenta.addItem(String.valueOf(cuenta.getIdCuenta()));
            }

        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar cuentas");
        }
    }
    
    private void cargarTiposOperacion() {
        cmbTipoOperacion.removeAllItems();
        cmbTipoOperacion.addItem("DEPOSITO");
        cmbTipoOperacion.addItem("RETIROSINTARJETA");
        cmbTipoOperacion.addItem("TRANSFERENCIA");
    }
    
    
    private void crearOperacion() {

        try {

            String tipoOperacion = (String) cmbTipoOperacion.getSelectedItem();
            String idCuentaTexto = (String) cmbIdCuenta.getSelectedItem();
            Integer idCuenta = Integer.parseInt(idCuentaTexto);

            
            GregorianCalendar fechaHora = new GregorianCalendar();

            NuevaOperacionDTO nuevaOperacion = new NuevaOperacionDTO(fechaHora, tipoOperacion, idCuenta);

            operacionesBO.crearOperacion(nuevaOperacion);

            JOptionPane.showMessageDialog(this, "Operacion creada correctamente");

        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error inesperado");
        }
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblFechaHora = new javax.swing.JLabel();
        txtFechaHora = new javax.swing.JTextField();
        cmbTipoOperacion = new javax.swing.JComboBox<>();
        lblTipoOperacion = new javax.swing.JLabel();
        lbIdCuenta = new javax.swing.JLabel();
        cmbIdCuenta = new javax.swing.JComboBox<>();
        btnSalir = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Operaciones");

        lblFechaHora.setText("Fecha y Hora:");

        cmbTipoOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblTipoOperacion.setText("TipoOperacion");

        lbIdCuenta.setText("ID Cuenta:");

        cmbIdCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSalir.setText("Salir");

        btnContinuar.setText("Continuar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTipoOperacion)
                                .addGap(18, 18, 18)
                                .addComponent(cmbTipoOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 101, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbIdCuenta)
                                .addGap(36, 36, 36)
                                .addComponent(cmbIdCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFechaHora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaHora)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btnSalir)
                .addGap(59, 59, 59)
                .addComponent(btnContinuar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdCuenta)
                    .addComponent(cmbIdCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaHora)
                    .addComponent(txtFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoOperacion)
                    .addComponent(cmbTipoOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnContinuar))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbIdCuenta;
    private javax.swing.JComboBox<String> cmbTipoOperacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbIdCuenta;
    private javax.swing.JLabel lblFechaHora;
    private javax.swing.JLabel lblTipoOperacion;
    private javax.swing.JTextField txtFechaHora;
    // End of variables declaration//GEN-END:variables
}
