/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectotransferencia.presentacion;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JOptionPane;
import proyectotransferencia.dtos.NuevaCuentaDTO;
import proyectotransferencia.entidades.Cliente;
import proyectotransferencia.negocio.IClientesBO;
import proyectotransferencia.negocio.ICuentaBO;
import proyectotransferencia.negocio.NegocioException;

/**
 *
 * @author PC GAMER MASTER RACE
 */
public class NuevaCuentaFORM extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NuevaCuentaFORM.class.getName());
    private final ICuentaBO cuentaBO;
    private final IClientesBO clienteBO;

    /**
     * Creates new form NuevaCuentaFORM
     */
    public NuevaCuentaFORM(ICuentaBO cuentaBO, IClientesBO clienteBO) {
        this.cuentaBO = cuentaBO;
        this.clienteBO = clienteBO;
        initComponents();

        cargarClientes();

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        GregorianCalendar calendario = new GregorianCalendar();
        Date fechaActual = calendario.getTime();

        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

        txtFechaApertura.setText(formato.format(fechaActual));
        txtFechaApertura.setEditable(false);
    }
    
    private void crearCuenta() {
    try {
        
        if (cmbClientes.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente");
            return;
        }
        
        String clienteSeleccionado = (String) cmbClientes.getSelectedItem();
        String[] partes = clienteSeleccionado.split(" - ");
        Integer idCliente = Integer.parseInt(partes[0]);
        String numeroCuenta = this.txtNumeroCuenta.getText();
        String fechaAperturaTexto = this.txtFechaApertura.getText();
        String saldoTexto = this.txtSaldo.getText();

        if (numeroCuenta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El Numero de Cuenta es Obligatorio");
            return;
        }

        if (saldoTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El Saldo es Obligatorio");
            return;
        }

        Double saldo = Double.parseDouble(saldoTexto);

        if (saldo < 0) {
            JOptionPane.showMessageDialog(this, "El Saldo no Puede ser Negativo");
            return;
        }

        
        SimpleDateFormat formateador = new SimpleDateFormat("dd/MM/yyyy");
        long fechaMilis = formateador.parse(fechaAperturaTexto).getTime();

        GregorianCalendar fechaApertura = new GregorianCalendar();
        fechaApertura.setTimeInMillis(fechaMilis);

        // 🔥 Estado por defecto
        String estado = "ACTIVA";

        NuevaCuentaDTO nuevaCuenta = new NuevaCuentaDTO(
                numeroCuenta,
                fechaApertura,
                saldo,
                estado,
                idCliente
        );

        this.cuentaBO.crearCuenta(nuevaCuenta);
        JOptionPane.showMessageDialog(this, "Cuenta Guardada Con Exito", "Información", JOptionPane.INFORMATION_MESSAGE);
        }catch(ParseException ex){
            JOptionPane.showMessageDialog(this, "La Fecha de Registro tiene formato inválido", "Error", JOptionPane.INFORMATION_MESSAGE);
        }catch(NegocioException ex){
            //TODO
        }

    }
    
    private void cargarClientes() {
    try {
        cmbClientes.removeAllItems(); // limpia el modelo

        List<Cliente> clientes = clienteBO.obtenerClientes();

        for (Cliente c : clientes) {
            String item = c.getIdCliente() + " - " 
                        + c.getNombre() + " " 
                        + c.getApellidoPaterno();

            cmbClientes.addItem(item);
        }

    }catch (NegocioException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumCuenta = new javax.swing.JLabel();
        lblFechaApertura = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroCuenta = new javax.swing.JTextField();
        txtFechaApertura = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        cmbClientes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNumCuenta.setText("Numero de Cuenta:");

        lblFechaApertura.setText("Fecha Apertura:");

        lblSaldo.setText("Saldo: ");

        jLabel4.setText("Id Cliente");

        btnCancelar.setText("Cancelar");

        btnCrear.setText("Crear");
        btnCrear.addActionListener(this::btnCrearActionPerformed);

        cmbClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clientes" }));
        cmbClientes.addActionListener(this::cmbClientesActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(lblNumCuenta)
                            .addComponent(lblFechaApertura)
                            .addComponent(lblSaldo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumeroCuenta)
                    .addComponent(txtFechaApertura)
                    .addComponent(txtSaldo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 104, Short.MAX_VALUE))
                    .addComponent(cmbClientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumCuenta)
                    .addComponent(txtNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaApertura)
                    .addComponent(txtFechaApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaldo)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnCrear))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        this.crearCuenta();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void cmbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbClientesActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt){
       this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JComboBox<String> cmbClientes;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblFechaApertura;
    private javax.swing.JLabel lblNumCuenta;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JTextField txtFechaApertura;
    private javax.swing.JTextField txtNumeroCuenta;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
